[package]
name = "micorm"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "3.1.0"
serde = "1.0.215"
async-trait = "0.1.83"
uuid = { version = "1.11.0", features = ["v4", "serde", "fast-rng"] }
micorm_derive = {path = "micorm_derive"}
